version: "3"
name: "vhm-tools"
services:
  postgres:
    image: postgres:14
    ports:
      - 2340:5432
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'vhm-tools']
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_USER: vhm-tools
      POSTGRES_PASSWORD: vhm-tools
      POSTGRES_DB: vhm-tools

  redis:
    image: redis
    ports:
      - 9730:6379
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 30s
      retries: 3

networks:
  vhm_tools:
    driver: bridge
