version: "3"
name: "vhm-tools"
services:
  user_service:
    image: 102205/tools-user-service:1.0
    container_name: user_service-tools
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - 1515:1515
    networks:
      - vhm_tools
    depends_on:
      - pg_tools
      - redis_tools

networks:
  vhm_tools:
    name: vhm-tools-nw
    external: true

